name: Robot Framework API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      actions: read

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Show environment info (basic debug)
      run: |
        echo "Python version: $(python --version)"
        echo "Working directory: $(pwd)"
        echo "Listing root files:"
        ls -lah

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        mkdir -p results
        python -m robot --outputdir results tests/

    - name: Debug result directory
      run: |
        echo "Checking contents of 'results/' directory:"
        if [ -d "results" ]; then
          ls -lah results
        else
          echo "'results' directory not found!"
          exit 1
        fi

    - name: Show environment variables (hardcore debug)
      run: printenv

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: results/
